### ISSUE TITLE
Configure Fabman account ID instead of checking the FIRST member

### ISSUE THREAD

**Issue by rluba** [rplnt/octoprint-fabman-auth#1]
First, let me say thanks for integrating Fabman and Octoprint! 

May I suggest a small improvement? Instead of [always selecting the first member of a user](https://github.com/rplnt/octoprint-fabman-auth/blob/ee36008d078207d8853ffd877d000d36726334f3/__init__.py#L80), you might add a config value "Fabman account ID" and search the user’s members for a member where `member.account == <fabman account id>`. Otherwise you’ll run into problems as soon as a user is a member of more than one Fabman account.

**Comment by rplnt** [comment]
Thanks! I actually wasn't exactly sure why there is an array of members under an user, and since I only saw single-member accounts I used [0]. Hope this fixes that.

**Comment by rluba** [comment]
Looks good to me. 👍
